[package]
name = "dear-imnodes"
version = "0.7.1"
edition.workspace = true
description = "Safe, idiomatic Rust bindings for ImNodes (node editor for Dear ImGui)"
license.workspace = true
repository.workspace = true
homepage.workspace = true
categories.workspace = true
keywords.workspace = true

[dependencies]
dear-imgui-rs = { path = "../../dear-imgui", version = "0.7" }
dear-imnodes-sys = { path = "../dear-imnodes-sys", version = "0.7" }
bitflags.workspace = true
thiserror.workspace = true

[features]
default = []
# Docking is always enabled; remove feature.
# Enable multi-viewport support (commented out while WIP)
# multi-viewport = ["dear-imgui-rs/multi-viewport", "dear-imnodes-sys/multi-viewport"]
freetype = ["dear-imgui-rs/freetype", "dear-imnodes-sys/freetype"]
wasm = ["dear-imgui-rs/wasm", "dear-imnodes-sys/wasm"]

[dev-dependencies]
static_assertions = "1.1"
