[package]
name = "dear-implot"
version = "0.7.0"
edition.workspace = true
description = "High-level Rust bindings to ImPlot with dear-imgui-rs integration"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/dear-implot"
categories.workspace = true
keywords.workspace = true
readme = "README.md"

[package.metadata.docs.rs]
features = ["freetype"]

[dependencies]
bitflags.workspace = true
dear-imgui-rs = { path = "../../dear-imgui", version = "0.7" }
dear-implot-sys = { path = "../dear-implot-sys", version = "0.7" }
dear-imgui-sys = { path = "../../dear-imgui-sys", version = "0.7" }
#mint.workspace = true
#parking_lot.workspace = true
#cfg-if.workspace = true
#thiserror.workspace = true

[features]
default = []
# Enable linking the ImPlot demo symbols (off by default)
demo = []
# Docking is always enabled; remove feature.
# Enable multi-viewport support (commented out while WIP)
# multi-viewport = ["dear-imgui-rs/multi-viewport", "dear-implot-sys/multi-viewport"]
# Enable freetype font rasterizer
freetype = ["dear-imgui-rs/freetype", "dear-implot-sys/freetype"]
# Enable for WASM targets
wasm = ["dear-imgui-rs/wasm", "dear-implot-sys/wasm"]

[dev-dependencies]
approx = "0.5"
pretty_assertions = "1.4"
static_assertions = "1.1"
