[package]
name = "dear-implot3d"
version = "0.7.0"
edition.workspace = true
description = "High-level Rust bindings to ImPlot3D with dear-imgui-rs integration"
license.workspace = true
repository.workspace = true
homepage.workspace = true
documentation = "https://docs.rs/dear-implot3d"
categories.workspace = true
keywords.workspace = true
readme = "README.md"

[package.metadata.docs.rs]
features = []

[dependencies]
bitflags.workspace = true
dear-imgui-rs = { path = "../../dear-imgui", version = "0.7" }
dear-implot3d-sys = { path = "../dear-implot3d-sys", version = "0.7" }
dear-imgui-sys = { path = "../../dear-imgui-sys", version = "0.7" }
mint = { workspace = true, optional = true }

[features]
default = []
mint = ["dep:mint"]
wasm = ["dear-imgui-rs/wasm", "dear-implot3d-sys/wasm"]
